### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by ctron** [rp-rs/rp2040-boot2-rs#4]
I tried to build the `sample-project`, but ran into the issue building this dependency:

~~~
   Compiling rp2040-boot2 v0.1.2 (https://github.com/rp-rs/rp2040-boot2-rs?branch=main#46247ee8)
error: failed to run custom build command for `rp2040-boot2 v0.1.2 (https://github.com/rp-rs/rp2040-boot2-rs?branch=main#46247ee8)`

Caused by:
  process didn't exit successfully: `/home/jreimann/git/rp2040/sample-project/target/debug/build/rp2040-boot2-d0839fa6c22a037b/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'executing arm-none-eabi-gcc: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/jreimann/.cargo/git/checkouts/rp2040-boot2-rs-b6d9ce848d516f57/46247ee/build.rs:20:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
~~~

Looks like I am missing `arm-none-eabi-gcc`, so I installed it on Fedora 34, which suggests the following:

~~~
The following packages have to be installed:
 arm-none-eabi-gcc-cs-1:10.2.0-4.fc34.x86_64    GNU GCC for cross-compilation for arm-none-eabi target
~~~

However, that now results in:

~~~
error: failed to run custom build command for `rp2040-boot2 v0.1.2 (https://github.com/rp-rs/rp2040-boot2-rs?branch=main#46247ee8)`

Caused by:
  process didn't exit successfully: `/home/jreimann/git/rp2040/sample-project/target/debug/build/rp2040-boot2-d0839fa6c22a037b/build-script-build` (exit status: 101)
  --- stderr
  arm-none-eabi-gcc: fatal error: cannot read spec file 'nosys.specs': No such file or directory
  compilation terminated.
  thread 'main' panicked at 'asm compile failed: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "arm-none-eabi-gcc: fatal error: cannot read spec file 'nosys.specs': No such file or directory\ncompilation terminated.\n" }', /home/jreimann/.cargo/git/checkouts/rp2040-boot2-rs-b6d9ce848d516f57/46247ee/build.rs:23:9
~~~

It would be helpful to understand what needs to be installed in order to compile this.

**Comment by LU15W1R7H** [comment]
I'm experiencing the same problem.

**Comment by ctron** [comment]
I ended up downloading an "xpack" which contains the compiler pre-built. Doing a manually install worked fine for me (as I didn't want to install yet another package manager): https://xpack.github.io/arm-none-eabi-gcc/install/#manual-install

**Comment by LU15W1R7H** [comment]
@ctron Okay, thanks. I'll take a look.

**Comment by thejpster** [comment]
You probably need to install newlib (a libc which supports embedded platforms) to go with your GCC.

**Comment by 9names** [comment]
Best option if you don't want to build/install newlib is to grab your toolchain direct from ARM.
They supply a tested+supported toolchain with newlib for all cortex a/r/m/ processors across most platforms with a regular release cadence.
https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads

I think we've covered why this is happening and how to resolve this, closing this issue.
