### ISSUE TITLE
Feature request: build all boot2 variants at once

### ISSUE THREAD

**Issue by 9names** [rp-rs/rp2040-boot2-rs#6]
As discussed in #5, we now have multiple SPI flash chips supported, and in the future there may be many of these.
Because we want to keep boot2 as small as possible, building support for all chips into the one binary is unfeasible - we must build a different boot2 binary for each target.
Currently, we choose which boot2 to build based on feature flags, so we can use the same main.rs for each target
```Rust
pub static BOOT2: [u8; 256] = rp2040_boot2::BOOT_LOADER;
```
The suggestion here is that we build them all and export all the different variants, so you can have a multi-binary project that builds for different targets. This would also help a new user who isn't confident with Cargo.toml features yet.
```Rust
// For Pico
pub static BOOT2: [u8; 256] = rp2040_boot2::BOOT_LOADER_PICO;
// For Arduino connect
pub static BOOT2: [u8; 256] = rp2040_boot2::BOOT_LOADER_ARDUINO_CONNECT;
```
We will keep rp2040_boot2::BOOT_LOADER as the Pico boot2 by default so that existing code continues to work.
If possible, we should also allow feature flags to select what `rp2040_boot2::BOOT_LOADER` provides so users can switch between targets without changing their source files - though I think that perhaps Board Support Packages would be better placed to provide this functionality.

**Comment by taunusflieger** [comment]
I think this is a good approach been able to control which boot2 gets created through features and create all variants. One slight correction - this will not reduce the size of the boot loader, as with the feature approach today only the selected variant gets compiled

```Rust
let target = if cfg!(feature = "ram_memcpy") {
        "src/boot2_ram.S"
      } else if cfg!(feature = "xip") {
        "src/boot2_w25q080.S"
      } else {
        unreachable!()
      };
    let elf = make_elf(target, &out_dir);
```

I'm volunteering to create a PR for this.

**Comment by taunusflieger** [comment]
I've looked into it. What I don't understand is why would we need a multi-binary project? rp2040_boot2 is a library. The boot loader is exported as a symbol. If we have multiple boot loader they are all exported, but only the one which is actually used will be linked to the target. So having multiple boot loader within a single binary will not blow up the size of the target. What is the benefit of a multi-binary project in this case?
In addition should we keep the feature approach - for backwards compatibility it might make sense, but it will add additional complexity in build.rs and maintenance (adding new boot loaders) will become more difficult. I would suggest to drop the feature approach. Thoughts?

The boot loaders would be exported like this:

```Rust
pub static BOOT_LOADER: [u8; 256] = *include_bytes!(concat!(env!("OUT_DIR"), "/boot2_padded_xip.bin"));
pub static BOOT_LOADER_ARDUINO_CONNET: [u8; 256] = *include_bytes!(concat!(env!("OUT_DIR"), "/boot2_padded_at25sf128a.bin"));
pub static BOOT_LOADER_RAM: [u8; 256] = *include_bytes!(concat!(env!("OUT_DIR"), "/boot2_padded_ram.bin"));
```

**Comment by 9names** [comment]
Sorry, I think I didn't clearly state the intent here.
> If we have multiple boot loader they are all exported, but only the one which is actually used will be linked to the target.

What you're describing sounds exactly like what we're after.
@thejpster made a PR already #7, does this match with what you're describing?

**Comment by taunusflieger** [comment]
@9names no worries - yes that is what I've described. I've looked through #7 - very similar to my proposal except, that I would vote to drop features now. I don't think too many people will be impacted - at least less than if we wait longer. In the long run I don't see the use-case for having both approaches. The solution becomes cleaner if there is only one approach implemented. My 2 cent.

**Comment by 9names** [comment]
Well that sounds like 2 votes for fixing it now vs my preference to keep it as-is until the next version. Probably for the best we do it now and get it over with then.
We already pinned the boot2 version in the HAL to the current git commit, so we're not going to cause problems for anyone using that.
Only one of the BSPs is configured to get it's boot2 from git main, shouldn't have much impact.
